### ISSUE TITLE
Worldgate randomly crashes the game.

### ISSUE THREAD

**Issue by Alatarius** [EmptyStar/worldgate#4]
I was just exploring in creative in a new singleplayer world and I will intermittently have the game crash with this error;
```
`AsyncErr:` Lua: Runtime error from mod 'worldgate' in callback environment_OnGenerated(): D:\Games\Minetest\bin\..\builtin\common\item_s.lua:229: bad argument #1 to '__index' (string expected, got nil)
stack traceback:
	[C]: in function '__index'
	D:\Games\Minetest\bin\..\builtin\common\item_s.lua:229: in function <D:\Games\Minetest\bin\..\builtin\common\item_s.lua:228>
	[C]: in function 'swap_node'
	D:\Games\Minetest\bin\..\mods\worldgate/src/mapgen.lua:269: in function <D:\Games\Minetest\bin\..\mods\worldgate/src/mapgen.lua:89>
	D:\Games\Minetest\bin\..\builtin\common\register.lua:26: in function <D:\Games\Minetest\bin\..\builtin\common\register.lua:12>
```

[edit]
This happens whenever a worldgate comes into view and gets rendered

**Comment by EmptyStar** [comment]
I think I know how I can prevent this crash, but I'm a little bit curious about your situation. Any answers to the below questions might be helpful. In the meantime, I'm going to cook up what I believe will be a quick and simple fix for this.

- What version of Minetest are you using?
- Are you running Minetest on Windows or another platform/OS?
- Does this happen every time a worldgate attempts to generate or does it only happen sometimes/occasionally/rarely?

**Comment by EmptyStar** [comment]
I wasn't able to reproduce this crash in my own testing, but I just pushed a fix that should mitigate this crash. Please check out the new version, v1.2.1, which should hopefully get it working for you.

**Comment by Alatarius** [comment]
To answer your questions 

What version of Minetest are you using?

-mt 5.8.0 playing mt_game in singleplayer


Are you running Minetest on Windows or another platform/OS?
-Windows 11 pro

Does this happen every time a worldgate attempts to generate or does it only happen sometimes/occasionally/rarely?
-Every time



⁣Get BlueMail for Android ​

**Comment by Alatarius** [comment]
I will try that and let you know

⁣Get BlueMail for Android ​

**Comment by Alatarius** [comment]
It's not crashing at the moment, so thank you for that. In-game I have found 3 but it looks like those 3 were broken during world-gen. Is there a wiki or something explaining how they work and/or how to build one?

**Comment by EmptyStar** [comment]
There is no wiki, but there is [API documentation](https://github.com/EmptyStar/worldgate/blob/main/API.md) if you want to define your own worldgates, or you might want to look at [the Telemosaic mod](https://content.minetest.net/packages/mt-mods/telemosaic/) for more information about how the teleportation works. Any worldgates that were broken when your game crashed will likely need to be repaired manually using teleportation extenders (can be crafted or found in the creative inventory).

I'm sorry that Worldgate has been working so poorly for you. I've done extensive testing and no one else has reported such major breaking issues. I'm wondering if maybe there's an incompatibility with another mod or something. Have you tried Worldgate with just plain Minetest Game and no other mods?
